<?php
/**
 * @file
 */

/**
 * Implements hook_d2d_secure_rpc().
 */
function d2d_passport_d2d_secure_rpc() {

  $methods = array();
  $methods['d2d_passport_get_users_number'] = array(
    'arguments' => array(),
    'callback' => '_d2d_passport_get_users_number',
    'description' => 'Returns the number of users in this website.',
  );
  $methods['d2d_passport_get_site_information'] = array(
    'arguments' => array(),
    'callback' => '_d2d_passport_get_site_information',
    'description' => 'Returns the title and the slogan of this website.',
  );
  $methods['d2d_passport_get_nodes_number'] = array(
    'arguments' => array(),
    'callback' => '_d2d_passport_get_nodes_number',
    'description' => 'Returns the number of nodes created so far in this website.',
  );
  $methods['d2d_passport_get_tags'] = array(
    'arguments' => array(),
    'callback' => '_d2d_passport_get_tags',
    'description' => 'Returns the D2D tags inserted in the configuration page.',
  );
  return $methods;
}

/**
 */
function _d2d_passport_get_users_number($arguments, $rpc_info) {
  $error_string = NULL;
  $users_number = NULL;

  $query = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->condition('status', 1, '=')
    ->execute();

  $users_number = $query->rowCount();

  return d2d_implode(array('return' => $users_number, 'error' => $error_string));

}

/**
 */
function _d2d_passport_get_site_information($arguments, $rpc_info) {
  $error_string = NULL;
  $return = array();

  $return['name'] = variable_get('site_name', '');
  $return['slogan'] = variable_get('site_slogan', '');

  $return = d2d_implode($return);
  return d2d_implode(array('return' => $return, 'error' => $error_string));
}

/**
 */
function _d2d_passport_get_nodes_number($arguments, $rpc_info) {
  $error_string = NULL;
  $nodes_number = NULL;

  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('status', 1, '=')
    ->execute();

  $nodes_number = $query->rowCount();

  return d2d_implode(array('return' => $nodes_number, 'error' => $error_string));

}

/**
 */
function _d2d_passport_get_tags($arguments, $rpc_info) {
  $error_string = NULL;
  $return = variable_get('d2d_passport_instance_tags', '');
  return d2d_implode(array('return' => $return, 'error' => $error_string));
}

/**
 * d2d_passport_configure_form
 */
function d2d_passport_configure_form($form, &$form_state) {
  $form = array();
  $form['tags'] = array(
    '#type' => 'fieldset',
    '#title' => 'D2D Tags',
    '#description' => t('Insert here a few keywords that properly identify your site. These keywords will be used to index your instance on the D2D server'),
  );
  $form['tags']['text'] = array(
    '#type' => 'textfield',
    // '#title' => 'tags',
    '#description' => 'Separate multiple tags with a comma.',
    '#default_value' => variable_get('d2d_passport_instance_tags', ""),
    '#size' => 50,
  );
  $form['tags']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function d2d_passport_configure_form_submit(&$form, &$form_state) {
  if (empty($form_state['values']['text'])) {
    drupal_set_message("Please enter some words.", "error");
    return;
  }
  variable_set('d2d_passport_instance_tags', $form_state['values']['text']);
  drupal_set_message("Tags Save Successfully. D2D Server will fetch them later.");
}

/**
 * Implements hook_menu()
 */
function d2d_passport_menu() {
  $items['admin/d2d/passport'] = array(
    'title' => 'D2D Passport',
    //'page callback' => 'drupal_get_form',
    'page callback' => 'd2d_passport_configure_page',
    //'page arguments' => array('d2d_passport_configure_form'),
    'access arguments' => array('administer d2d'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 81,
  );
  return $items;
}


function d2d_passport_configure_page() {
  $hks = module_invoke('d2d_passport', 'd2d_secure_rpc');
  $header = array(
    'method_name' => t('Method Name'),
    'method_description' => t('method_description'),
  );

  $rows = array();
  foreach ($hks as $key => $value) {
    $rows[$key][] = $key;
    $rows[$key][] = isset($value['description']) ? $value['description'] : '';
  }
  $check = l(t('Make sure that the permissions are correctly set.'), 'admin/d2d/g_and_p/permissions');
  //$rows[] = array('<div id="d2d-passport-check-permission">' . $check . "</div>", NULL);
  $rows[] = array('<strong>' . $check . "</strong>", NULL);

  $page = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('class' => array('patterns-server-list-table'))));

  $form = drupal_get_form('d2d_passport_configure_form');
  $page .= drupal_render($form);

  return $page;
}
